# Generated by Django 4.0.4 on 2022-05-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BigIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('logo', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.BigIntegerField()),
                ('lingitude', models.BigIntegerField()),
                ('adress', models.CharField(blank=True, default='', max_length=50)),
                ('additionalinfo', models.TextField(blank=True, default='')),
                ('work_schedule', models.JSONField()),
                ('currency_type', models.CharField(default='UAH', max_length=3)),
                ('timestamp_create', models.DateField(auto_now=True)),
                ('timestamp_update', models.DateField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Fuelinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('fuel_type', models.CharField(choices=[('D', 'Diesel'), ('D', 'Gasoline'), ('G', 'Gas')], default='None', max_length=15)),
                ('quantity_limit', models.BigIntegerField(verbose_name='How many liters?')),
                ('avallabilly', models.BooleanField()),
                ('timestamp_create', models.DateField(auto_now=True)),
                ('timestamp_update', models.DateField(auto_now_add=True)),
                ('staItionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Station', to='api.station')),
            ],
        ),
    ]
