# Generated by Django 4.0.4 on 2022-05-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_station_fuelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
